eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka
  instance:
    hostname: localhost
    
  microservices:
    order-services:
      endpoints:
        endpoint:
          uri: http://localhost:9091/book/bookOrder
    payment-services:
      endpoints:
        endpoint:
          uri: http://PAYMENT-SERVICE/payment/payForOrder
          
    
 
